#!/bin/bash

#PBS -A eecs587f14_flux
#PBS -l qos=flux
#PBS -q flux
#PBS -l nodes=2,walltime=00:00:05
#PBS -o o.txt
#PBS -e e.txt
module load gcc/4.8.0
module load openmpi/1.8.2/gcc/4.8.0

cd /home/drings/Parallel
(mpirun ./hw3 25 500) > hw3Out.txt
